### ISSUE TITLE
NPM ERR! when executing release.sh

### ISSUE THREAD

**Issue by arbaldin** [lmangani/timelion-influxdb#2]
I'd edited the package.json to include kibana version 6.6.2, but I always receive an error when trying to execute the release.sh script.

The packege.json file:

{
  "name": "timelion-influxdb",
  "version": "1.0.0",
  "kibana": {
    "version": "6.6.2"
  },
  "kibanas": [
    "6.2.2",
    "6.2.3",
    "6.2.4",
    "6.6.2"
  ],
  "description": "Timelion plugin to read data from influxdb",
  "main": "gulpfile.js",
  "scripts": {
    "start": "gulp dev",
    "build": "gulp build",
    "package": "gulp package",
    "test": "gulp test"
  },
  "devDependencies": {
    "@elastic/eslint-config-kibana": "^0.1.0",
    "babel-eslint": "^4.1.8",
    "bluebird": "^3.1.1",
    "eslint": "^1.10.3",
    "eslint-plugin-mocha": "^1.1.0",
    "glob": "^7.0.5",
    "gulp": "^3.9.0",
    "gulp-eslint": "^1.1.1",
    "gulp-gzip": "^1.2.0",
    "gulp-tar": "^1.8.0",
    "gulp-util": "^3.0.7",
    "gulp-zip": "^3.2.0",
    "lodash": "^3.10.1",
    "mkdirp": "^0.5.1",
    "rimraf": "^2.5.0",
    "rsync": "^0.4.0"
  },
  "dependencies": {
    "babel-register": "^6.3.13",
    "lodash": "^4.17.2"
  }
}

The error after executing VERSION="6.6.2" ./release.sh

Patching with version 6.6.2 ...
npm ERR! Linux 3.10.0-957.5.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! file /tmp/tmp.p1BZ1Lbgeq/kibana/timelion-influxdb/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 6:3
npm ERR!   },
npm ERR!   ^
npm ERR! File: /tmp/tmp.p1BZ1Lbgeq/kibana/timelion-influxdb/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/tmp.p1BZ1Lbgeq/kibana/timelion-influxdb/npm-debug.log
  adding: kibana/ (stored 0%)
  adding: kibana/timelion-influxdb/ (stored 0%)
  adding: kibana/timelion-influxdb/dist/ (stored 0%)
  adding: kibana/timelion-influxdb/functions/ (stored 0%)
  adding: kibana/timelion-influxdb/functions/influxdb.js (deflated 65%)
  adding: kibana/timelion-influxdb/index.js (deflated 37%)
  adding: kibana/timelion-influxdb/LICENSE (deflated 65%)
  adding: kibana/timelion-influxdb/package.json (deflated 60%)
  adding: kibana/timelion-influxdb/README.md (deflated 60%)
  adding: kibana/timelion-influxdb/release.sh (deflated 49%)
  adding: kibana/timelion-influxdb/npm-debug.log (deflated 61%)
-rw-r--r--. 1 root root 11015 Mar 19 14:58 timelion-influxdb-6.6.2.zip
Done! Archive timelion-influxdb-6.6.2.zip ready.

I tried to remove the comma in line 6, but it didn't work either.

**Comment by lmangani** [comment]
`release` seems to be adding a comma where it shouldn't - just patch your `package.json` and run release without a version to bypass the problem for now. Thanks!
